import { Task, TaskStatus, User } from './types';

export const USERS: User[] = [
  { id: 'u1', name: '王强 (Alex)', role: 'Manager', avatar: 'https://picsum.photos/seed/alex/100/100' },
  { id: 'u2', name: '陈莎莎 (Sarah)', role: 'Contributor', avatar: 'https://picsum.photos/seed/sarah/100/100' },
  { id: 'u3', name: '李明 (Mike)', role: 'Contributor', avatar: 'https://picsum.photos/seed/mike/100/100' },
  { id: 'u4', name: '赵敏 (Emily)', role: 'Contributor', avatar: 'https://picsum.photos/seed/emily/100/100' },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Q3 财务报表分析',
    assigneeId: 'u2',
    status: TaskStatus.IN_PROGRESS,
    planContent: '汇总销售、市场和运营数据。创建数据透视表进行分析。',
    actualContent: '数据收集已完成 80%。正在等待市场部的最终数据。',
    planHours: 8,
    actualHours: 5,
    deadline: new Date(Date.now() + 86400000).toISOString(),
    lastUpdated: new Date().toISOString(),
    updatedBy: 'u2',
  },
  {
    id: 't2',
    title: '更新落地页 Hero 区域',
    assigneeId: 'u3',
    status: TaskStatus.DONE,
    planContent: '设计新的 Banner，使用 React 实现并在测试环境部署。',
    actualContent: '设计和开发均已完成。已成功部署上线。',
    planHours: 4,
    actualHours: 3.5,
    deadline: new Date(Date.now() - 86400000).toISOString(),
    lastUpdated: new Date().toISOString(),
    updatedBy: 'u3',
  },
  {
    id: 't3',
    title: '后端 API 迁移',
    assigneeId: 'u3',
    status: TaskStatus.BLOCKED,
    planContent: '将旧版接口迁移至 Node.js v18 环境。',
    actualContent: '开始迁移但遇到认证服务的依赖冲突问题，暂时搁置。',
    planHours: 16,
    actualHours: 2,
    deadline: new Date(Date.now() + 172800000).toISOString(),
    lastUpdated: new Date().toISOString(),
    updatedBy: 'u3',
  },
  {
    id: 't4',
    title: '客户访谈总结',
    assigneeId: 'u4',
    status: TaskStatus.TODO,
    planContent: '回顾 5 个访谈录音，标记关键洞察，制作幻灯片。',
    actualContent: '',
    planHours: 6,
    actualHours: 0,
    deadline: new Date(Date.now() + 432000000).toISOString(),
    lastUpdated: new Date().toISOString(),
    updatedBy: 'u1',
  },
   {
    id: 't5',
    title: '团队产能规划',
    assigneeId: 'u1',
    status: TaskStatus.IN_PROGRESS,
    planContent: '审查 Q4 路线图并分配相应资源。',
    actualContent: '草拟了初步计划，需与陈莎莎确认细节。',
    planHours: 4,
    actualHours: 1,
    deadline: new Date(Date.now() + 86400000).toISOString(),
    lastUpdated: new Date().toISOString(),
    updatedBy: 'u1',
  },
];